Added list gist command.
thamaraiselvam/github-api-cli pull request #10
Opened 2019-10-22 15:13 UTC by samit22

Command: list gist
Should close https://github.com/thamaraiselvam/github-api-cli/issues/5

2019-10-22 16:28 UTC, thamaraiselvam reviewed
I really appreciate your PR. 

I have added a few comments, Please fix

2019-10-22 16:28 UTC, thamaraiselvam commented on cmd/publicGist.go
> +import (
Move this command under list command, check followers command for reference

2019-10-22 16:28 UTC, thamaraiselvam commented on cmd/root.go
> +	commands := []func() *cobra.Command{infoCmd, publicGistsCmd}
This change is not necessary once you moved gist command under list

2019-10-22 16:28 UTC, thamaraiselvam commented on cmd/service/service.go
> +	if resp.StatusCode == 500 {
In the latest changes, If the status code is not 200. we just return status whatever we get.

2019-10-22 16:28 UTC, thamaraiselvam commented on cmd/publicGist.go
> +	client := service.CreateClient("/gists/public")
How you are forming URL with given **<username>** as an argument?

2019-10-22 16:28 UTC, thamaraiselvam commented on cmd/types/types.go
> +type PublicGist struct {
Currently, the entire app is fetching only public data so please rename it into Gist

2019-10-22 16:28 UTC, thamaraiselvam commented on cmd/types/types.go
> +type PublicGist struct {
And you might need gists list to store gist

2019-10-22 16:29 UTC, thamaraiselvam requested changes
Please fix comments

2019-10-30 07:40 UTC, thamaraiselvam commented
Can you please resolve conflicts

2019-10-31 08:02 UTC, thamaraiselvam commented
Build is failing.

2019-10-31 09:11 UTC, thamaraiselvam commented on cmd/service/service.go
> +<<<<<<< HEAD
pushed along with conflicts?

2019-10-31 09:12 UTC, thamaraiselvam commented on cmd/types/types.go
> +type Gist struct {
this struct should be singular and can be named as `gist` then have list of `gist` called `Gists`

2019-10-31 09:14 UTC, thamaraiselvam commented on cmd/info.go
> +	"fmt"
this file needs to be removed since it is already moved inside of info dir

2019-10-31 09:14 UTC, thamaraiselvam commented on cmd/root.go
> +
This change is not necessary since `github.com/spf13/cobra` is already added

2019-10-31 09:19 UTC, samit22 commented
@thamaraiselvam This is work in progress.

2019-11-01 08:54 UTC, thamaraiselvam approved these changes

2019-11-01 08:54 UTC, thamaraiselvam commented
Thanks for the PR @samit22  👏🏼

2019-11-01 08:54 UTC, merged